CREATE TABLE ITEM (
  ITEM_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  ITEM_NAME VARCHAR(128) NOT NULL UNIQUE,
  ITEM_DESCRIPTION VARCHAR(256),
  ITEM_PRICE FLOAT NOT NULL,
  SELLER_NAME VARCHAR(256) NOT NULL,
  SELLER_EMAIL VARCHAR(256) NOT NULL
);